version: '3'
services:
  # my-app:
  #   image: 221082194376.dkr.ecr.eu-north-1.amazonaws.com/my-app:1.0
  #   ports:
  #     - 4000:4000
  mongodb:
    image: mongo:4.2.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express:0.49
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb